dist: trusty
sudo: false
language: python
python: 3.6
cache:
  apt: true
  pip: true
install:
  - pip install -U pip
  - pip install cython
  - pip install -U ucca
  - python -m spacy download en_core_web_md
env:
  global:
    - SCRIPTS=https://raw.githubusercontent.com/UniversalConceptualCognitiveAnnotation/docs/master/scripts
    - secure: "a6+qqw9s4418A1Wme1hTV3QFx0f2A0mp1B7Gma1+EVvVbhTVk9DTgNYaqxZlSGFplOyoWPpOYnppX7Bbbpd6GIsbYv871UxE3eTjX9/Wc038Hc2yWhusPbocmgyUvtI+d2npnawSm+ClOO6eto8VxSH9KB8G4YbPYT6YvQzEdcal8XHUuexHfFuq99ZpxO974EfASMHBTAHxxqIy7L3tJ2ZKgxzmg/g6j59BalYZJq3Kqnmt8eLMmMNLW3tyhA/dKz2AzH0hL2GWEJCB3TEUbPm0WdUs9Qa//HdHKodWqIC5OA4/TBIEK6b9nYR+r0Onf+cdvKvv0LvGaJVIIdH/rYRSpiBUT6IUen+c6UJOP6Cop7OYhsR9M23xkOGTnT9jghi9T3f+laT8I7GSg1Pn+1f4WpFUTlxijpxrVm8SbJxNdoYqLwglallVxtiGlGlr/vSiPJm+367jnBuPUuEszdRI74jXdhuHVgUGStEohC3HTgWiwBfImXczGHP40/oak/EipFy7zIyKCNJmLkfkf3cwYMy3WnLye6qO0NBL8+aWXZ9d/T9IsniUyZZcSBT4vylNekEdkYiZEOas3R0QiMqoYTxeGrZYErXjhcKuDo6Mw5xL0NDAjYZb3fUfBvwcyh/8MeWoGShkCWdkE5CeEnd2qfrZQRoDOstqxWMhdUE="
jobs:
  include:
    - script: python -m scripts.validate xml --no-linkage
    - stage: split
      script: curl $SCRIPTS/split_to_sentences.sh | bash
    - stage: convert
      script: curl $SCRIPTS/validate_sentences.sh | bash -s -- --no-linkage
      env: FORMAT=validate
    - script: curl $SCRIPTS/sentences_to_xml.sh | bash
      env: FORMAT=xml
    - script: curl $SCRIPTS/tupa.sh | bash
      env: FORMAT=tupa
    - script: curl $SCRIPTS/visualize.sh | bash
      env: FORMAT=visualize
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=sdp
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=conll
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=conllu
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=amr
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=export
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=txt
    - stage: evaluate
      script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=sdp
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=conll
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=conllu
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=amr
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=export
after_success: curl $SCRIPTS/push.sh | bash

